services:
  counter-service:
    container_name: counter-service-dev
    image: 143375183442.dkr.ecr.us-east-1.amazonaws.com/counter-service-dev:latest
    volumes:
      - ./data:/data
    ports:
      - "80:8080"
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpu: '0.5'
